{% set name = "pycoalescence" %}
{% set version = "1.2.6" %}
{% set sha256 = "93331c6481119dd83e30ffb361cfa2d4f28a2c0d4f1330fdf4068f60094e34ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv'
  detect_binary_files_with_prefix: True
  skip: True  # [(win and vc<14)]
  skip: True  # [linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake >=3.6

  host:
    - python
    - pip
    - setuptools
    - boost
    - gdal >=2.1.0
    - ncurses >=6.0.0  # [osx]
    - sqlite
    - matplotlib
    - numpy >=1.11.0

  run:
    - python
    - boost
    - {{ pin_compatible('gdal', max_pin='x.x') }}
    - {{ pin_compatible('ncurses', max_pin='x.x') }}  # [osx]
    - sqlite
    - matplotlib
    - numpy
    - scipy

test:
  imports:
    - pycoalescence
    - pycoalescence.necsim

about:
  home: https://bitbucket.org/thompsonsed/pycoalescence/
  license: MIT
  license_file: LICENSE.txt
  summary: 'Spatially-explicit neutral ecology simulator using coalescence methods'
  description: |
    pycoalescence is an API for easy interfacing with the necsim c++ neutral
    simulator for ecological models under the effects of
    dispersal, speciation and ecological drift in a spatially-explicit
    manner.
  doc_url: http://pycoalescence.readthedocs.io/
  dev_url: https://bitbucket.org/thompsonsed/pycoalescence/

extra:
  recipe-maintainers:
    - thompsonsed
