{% set name = "pycoalescence" %}
{% set version = "1.2.8.a1" %}
{% set sha256 = "886a50bc9ff1871b813519f87657c3119ce9a01529ceb621716548a07ebb1301" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # url: https://test-files.pythonhosted.org/packages/23/6a/4cc9a555bb6452ca87f202c11002d5daea0260243b7e50cc455ab4f3665a/pycoalescence-1.2.7.post20.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - cython

  host:
    - python
    - pip
    - setuptools
    - boost-cpp >=1.60.0
    - gdal >=2.1.0
    - sqlite
    - matplotlib
    - numpy >=1.11.0
    - configparser  # [py < 30]

  run:
    - python
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - {{ pin_compatible('gdal', max_pin='x.x.x') }}
    - sqlite
    - matplotlib
    - numpy
    - scipy
    - pandas
    - configparser  # [py < 30]
    - cython

test:
  imports:
    - pycoalescence
    - pycoalescence.necsim

about:
  home: https://github.com/thompsonsed/pycoalescence/
  license: MIT
  license_file: LICENSE.txt
  summary: 'Ecological simulator for spatially explicit neutral models using coalescence methods'
  description: |
    pycoalescence is an API for easy interfacing with the necsim c++ neutral
    simulator for ecological models under the effects of
    dispersal, speciation and ecological drift in a spatially-explicit
    manner.
  doc_url: http://pycoalescence.readthedocs.io/
  dev_url: https://github.com/thompsonsed/pycoalescence/

extra:
  recipe-maintainers:
    - thompsonsed
