{% set name = "pycoalescence" %}
{% set version = "1.2.9.post2" %}
{% set sha256 = "05f64fafaf005e437a424884ea3ce8420593bb11335456fff9038476bdd77319" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6

  host:
    - python
    - cython
    - pip
    - setuptools
    - boost-cpp >=1.60.0
    - gdal >=2.1.0
    - sqlite
    - matplotlib
    - numpy >=1.11.0
    - configparser  # [py < 30]
    - scikit-build

  run:
    - python
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - {{ pin_compatible('gdal', max_pin='x.x.x') }}
    - sqlite
    - matplotlib
    - numpy
    - scipy
    - pandas
    - configparser  # [py < 30]

test:
  imports:
    - pycoalescence
    - pycoalescence.necsim

about:
  home: https://github.com/thompsonsed/pycoalescence/
  license: MIT
  license_file: LICENSE.txt
  summary: 'Ecological simulator for spatially explicit neutral models using coalescence methods'
  description: |
    pycoalescence is an API for easy interfacing with the necsim c++ neutral
    simulator for ecological models under the effects of
    dispersal, speciation and ecological drift in a spatially-explicit
    manner.
  doc_url: http://pycoalescence.readthedocs.io/
  dev_url: https://github.com/thompsonsed/pycoalescence/

extra:
  recipe-maintainers:
    - thompsonsed
