{% set name = "pycoalescence" %}
{% set version = "1.2.7.post8" %}
{% set sha256 = "6303b30a109d423486895ceba0f0124f904d7a66d7df265c7856c96deed8d86c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 5
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv'
  detect_binary_files_with_prefix: True
  skip: True  # [(win and vc < 14)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6

  host:
    - python
    - pip
    - setuptools
    - boost-cpp >=1.60.0
    - gdal >=2.1.0
    - sqlite
    - matplotlib
    - numpy >=1.11.0
    - configparser  # [py < 30]

  run:
    - python
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - {{ pin_compatible('gdal', max_pin='x.x.x') }}
    - sqlite
    - matplotlib
    - numpy
    - scipy
    - pandas
    - configparser  # [py < 30]

test:
  imports:
    - pycoalescence
    - pycoalescence.necsim

about:
  home: https://bitbucket.org/thompsonsed/pycoalescence/
  license: MIT
  license_file: LICENSE.txt
  summary: 'Ecological simulator for spatially explicit neutral models using coalescence methods'
  description: |
    pycoalescence is an API for easy interfacing with the necsim c++ neutral
    simulator for ecological models under the effects of
    dispersal, speciation and ecological drift in a spatially-explicit
    manner.
  doc_url: http://pycoalescence.readthedocs.io/
  dev_url: https://bitbucket.org/thompsonsed/pycoalescence/

extra:
  recipe-maintainers:
    - thompsonsed
