travis:
  secure:
    BINSTAR_TOKEN: U9ihAlr7pSZmVfc5irvYbuEchSvTTolnvSl0ebHjP2k8SuNlpyJBL84JSHtL7ODF9CdDPCeIKatqk4W51sdkyXY4PS6WzBn87Uz7nO4AQe5EZCsmURLOz+vWZCuITSCvth1i1lK/X8hugd803VizhYALewTJggOhedp5chBjNY9kob8wGowyZSlgWLT6RYrn2KjSdJTubcL+1p5Uh2t74WlzMECUV7uc7tpLaDkTtptd1H9QG6Y+w5vvcP88ELPbyvUFwLy9GGxQh2iMb/SBrH8Kz4qVA5hOsUWNhqt7FYYFiDC4ciKSGyj+GCM87i6iX3Bw76Upa2DKSo2TzXZQb/6oCozw0kl9STP5X44kOBygs0tcmBuomQ0bSxfQTiVdFGnOz+5Lh1lRQeznLbwU1QLSRgnCARTSZD4HhLsh84QorhiK+r9dS3MBqkc/BoZyvt7HG8TETo7dpwQzbkXm07LEQH4Y/thKcyJ3hwI/sgubcJd4BbqQbtADtwJKHq0Lfra9v+XmmzL+PdhoCmXHt5Tlt2jhQzwUhhrQDa85NC1C0ajBubqclqdtv505pDSQJy093pI2vZ2RKo4QW+Tw+LZ77WjKqOyb9qQPreVjgBGEAkY88HD4nYzVvHXTajP9/O9/AIZE93r0Rfwxf3v0R9on1ZEkOW6XWhcIsnQC+VI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
