# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.14
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> fc77e24... Rerendered with conda-forge
  timeoutInMinutes: 360
>>>>>>> Rerendered with conda-forge
  strategy:
    matrix:
      osx_python3.6.____cpython:
        CONFIG: osx_python3.6.____cpython
<<<<<<< HEAD
<<<<<<< HEAD
        UPLOAD_PACKAGES: 'True'
      osx_python3.7.____cpython:
        CONFIG: osx_python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_python3.8.____cpython:
        CONFIG: osx_python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
    maxParallel: 8
  timeoutInMinutes: 360
=======
=======
>>>>>>> fc77e24... Rerendered with conda-forge
        UPLOAD_PACKAGES: True
      osx_python3.7.____cpython:
        CONFIG: osx_python3.7.____cpython
        UPLOAD_PACKAGES: True
>>>>>>> Rerendered with conda-forge

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
<<<<<<< HEAD
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
=======
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
>>>>>>> fc77e24... Rerendered with conda-forge
