# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      linux_64_numpy1.16python3.6.____cpython:
        CONFIG: linux_64_numpy1.16python3.6.____cpython
<<<<<<< HEAD
=======
=======
      linux_python3.6.____cpython:
        CONFIG: linux_python3.6.____cpython
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> Rerendered with conda-forge
=======
>>>>>>> 6b951ff (Rerendered with conda-forge)
>>>>>>> bef9287 (Rerendered with conda-forge)
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_numpy1.16python3.7.____cpython:
        CONFIG: linux_64_numpy1.16python3.7.____cpython
=======
>>>>>>> fa8a94f (Rerendered with conda-forge)
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_numpy1.16python3.8.____cpython:
        CONFIG: linux_64_numpy1.16python3.8.____cpython
=======
=======
>>>>>>> 9f152c5... Re-rendered with conda smithy
>>>>>>> 04268ed (Re-rendered with conda smithy)
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_numpy1.19python3.9.____cpython:
        CONFIG: linux_64_numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 99ef6e6 (Re-rendered with conda smithy)
=======
<<<<<<< HEAD
      linux_python3.6.____cpython:
        CONFIG: linux_python3.6.____cpython
=======
>>>>>>> 6b951ff (Rerendered with conda-forge)
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
=======
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
>>>>>>> fc77e24... Rerendered with conda-forge
      linux_python3.7.____cpython:
        CONFIG: linux_python3.7.____cpython
        UPLOAD_PACKAGES: True
>>>>>>> Rerendered with conda-forge
=======
>>>>>>> 9f152c5... Re-rendered with conda smithy
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

=======
      linux_python3.6.____cpython:
        CONFIG: linux_python3.6.____cpython
=======
      linux_64_python3.6.____cpython:
        CONFIG: linux_64_python3.6.____cpython
>>>>>>> Updated to 1.2.7post14
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_python3.7.____cpython:
        CONFIG: linux_64_python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_64_python3.8.____cpython:
        CONFIG: linux_64_python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
>>>>>>> bef9287 (Rerendered with conda-forge)
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
<<<<<<< HEAD
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
<<<<<<< HEAD
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
=======
<<<<<<< HEAD
<<<<<<< HEAD
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
=======
<<<<<<< HEAD
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
>>>>>>> Re-rendered with conda smithy
=======
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
>>>>>>> 9f152c5... Re-rendered with conda smithy
>>>>>>> Re-rendered with conda smithy
=======
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
>>>>>>> MNT: Re-rendered with conda-build 3.18.9, conda-smithy 3.7.3, and conda-forge-pinning 2020.05.19.09.34.36
=======
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
=======
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
>>>>>>> 9f152c5... Re-rendered with conda smithy
>>>>>>> 04268ed (Re-rendered with conda smithy)
>>>>>>> 99ef6e6 (Re-rendered with conda smithy)
